trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

  - task: NodeTool@0
    inputs:
      versionSpec: '12.16'
    displayName: 'Setup Environment'

  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
      workingDir: AdminClient/


  - task: Npm@1
    displayName: 'Build Angular'
    inputs:
      command: custom
      customCommand: run ng build
      workingDir: AdminClient/
      
  - task: Npm@1
    displayName: 'Tests'
    inputs:
      command: custom
      customCommand: run ng test -- --watch=false --no-progress --code-coverage=true 
      workingDir: AdminClient/

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
    displayName: 'Publish Test Results'

  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage/ng-azure-devops/cobertura-coverage.xml'
    displayName: 'Publish Code Coverage Results'



  - task: Maven@3
    inputs:
      mavenPomFile: 'Backend/OmegaSpring/pom.xml'
      goals: 'clean verify'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Docker@2
    inputs:
      containerRegistry: 'omegacr'
      repository: 'dev-backend'
      command: 'buildAndPush'
      Dockerfile: './Backend/OmegaSpring/Dockerfile'
      buildContext: './Backend/OmegaSpring'
      tags: |
        latest
        $(Build.BuildId)

  - task: Docker@2
    inputs:
      containerRegistry: 'omegacr'
      repository: 'dev-frontend'
      command: 'buildAndPush'
      Dockerfile: './AdminClient/Dockerfile'
      buildContext: './AdminClient'
      tags: |
        latest
        $(Build.BuildId)



  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default2'
      namespace: 'default'
      command: 'apply'
      arguments: '-f ./Devops/k8s'
      
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default2'
      namespace: 'default'
      command: 'set'
      arguments: 'image deployment/backend-deployment2 backend2-api=omegacr.azurecr.io/dev-backend:$(Build.BuildId)'
 
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'OmegaCluster-default2'
      namespace: 'default'
      command: 'set'
      arguments: 'image deployment/frontend-deployment frontend-adminclient=omegacr.azurecr.io/dev-frontend:$(Build.BuildId)'
 