apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'backend-deployment2'
spec:
  replicas: 5
  selector:
    matchLabels:
      component: backend2
  template:
    metadata:
      labels:
        app: omega
        component: backend2
    spec:
      containers:
        - name: backend2-api
          image: omegacr.azurecr.io/dev-backend
          ports:
            - containerPort: 5000
          env:
                - name: SECRETS_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: dev-db
                      key: SECRETS_DB_USERNAME
                - name: SECRETS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dev-db
                      key: SECRETS_DB_PASSWORD
                - name: SECRETS_DATABASE_NAME
                  valueFrom:
                      secretKeyRef:
                       name: dev-db
                       key: SECRETS_DB_NAME



