apiVersion: v1
kind: Service
metadata:
  name: backend-loadbalancer-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster

  selector:
    component: backend
  ports:
    - port: 80
      targetPort: 80
